In [1]:
import pandas as pd
store=pd.read_csv("../data/raw/store.csv")

In [12]:
df=pd.read_csv("../data/raw/train.csv")

C:\Users\pk629\AppData\Local\Temp\ipykernel_14184\1894540238.py:1: DtypeWarning: Columns (7: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("../data/raw/train.csv")

In [2]:
store.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [3]:
store.shape

(1115, 10)

In [4]:
store.columns

Index(['Store', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval'],
      dtype='str')

In [5]:
store.info()

<class 'pandas.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      1115 non-null   int64
 1   StoreType                  1115 non-null   str
 2   Assortment                 1115 non-null   str
 3   CompetitionDistance        1112 non-null   float64
 4   CompetitionOpenSinceMonth  761 non-null    float64
 5   CompetitionOpenSinceYear   761 non-null    float64
 6   Promo2                     1115 non-null   int64
 7   Promo2SinceWeek            571 non-null    float64
 8   Promo2SinceYear            571 non-null    float64
 9   PromoInterval              571 non-null    str
dtypes: float64(5), int64(2), str(3)
memory usage: 87.2 KB

In [6]:
store.isnull().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [13]:
missing = store.isnull().sum()

missing[missing > 0]

CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [14]:
store[store["CompetitionDistance"].isnull()]

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
290,291,d,a,NaN,NaN,NaN,0,NaN,NaN,NaN
621,622,a,c,NaN,NaN,NaN,0,NaN,NaN,NaN
878,879,d,a,NaN,NaN,NaN,1,5.0,2013.0,"Feb,May,Aug,Nov"

In [15]:
store[store["Promo2SinceWeek"].isnull()][
    ["Store", "Promo2", "Promo2SinceWeek", "Promo2SinceYear", "PromoInterval"]
].head(20)

    Store  Promo2  Promo2SinceWeek  Promo2SinceYear PromoInterval
0       1       0              NaN              NaN           NaN
3       4       0              NaN              NaN           NaN
4       5       0              NaN              NaN           NaN
5       6       0              NaN              NaN           NaN
6       7       0              NaN              NaN           NaN
7       8       0              NaN              NaN           NaN
8       9       0              NaN              NaN           NaN
9      10       0              NaN              NaN           NaN
15     16       0              NaN              NaN           NaN
22     23       0              NaN              NaN           NaN
24     25       0              NaN              NaN           NaN
25     26       0              NaN              NaN           NaN
28     29       0              NaN              NaN           NaN
30     31       0              NaN              NaN           NaN
32     33       0              NaN              NaN           NaN
33     34       0              NaN              NaN           NaN
36     37       0              NaN              NaN           NaN
37     38       0              NaN              NaN           NaN
43     44       0              NaN              NaN           NaN
44     45       0              NaN              NaN           NaN

In [16]:
store.shape

(1115, 10)

In [17]:
store.duplicated().sum()

np.int64(0)

In [18]:
store.describe()

,Store,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,1115.00000,1112.000000,761.000000,761.000000,1115.000000,571.000000,571.000000
mean,558.00000,5404.901079,7.224704,2008.668857,0.512108,23.595447,2011.763573
std,322.01708,7663.174720,3.212348,6.195983,0.500078,14.141984,1.674935
min,1.00000,20.000000,1.000000,1900.000000,0.000000,1.000000,2009.000000
25%,279.50000,717.500000,4.000000,2006.000000,0.000000,13.000000,2011.000000
50%,558.00000,2325.000000,8.000000,2010.000000,1.000000,22.000000,2012.000000
75%,836.50000,6882.500000,10.000000,2013.000000,1.000000,37.000000,2013.000000
max,1115.00000,75860.000000,12.000000,2015.000000,1.000000,50.000000,2015.000000

In [19]:
store["Store"].nunique()

1115

In [20]:
print("Store Type:")
print(store["StoreType"].value_counts())

print("\nAssortment:")
print(store["Assortment"].value_counts())

print("\nPromo2:")
print(store["Promo2"].value_counts())

Store Type:
StoreType
a    602
d    348
c    148
b     17
Name: count, dtype: int64

Assortment:
Assortment
a    593
c    513
b      9
Name: count, dtype: int64

Promo2:
Promo2
1    571
0    544
Name: count, dtype: int64

In [21]:
print("Stores in train:", df["Store"].nunique())
print("Stores in store:", store["Store"].nunique())

Stores in train: 1115
Stores in store: 1115

In [22]:
train_stores = set(df["Store"])
store_stores = set(store["Store"])

print("Stores in train but not store:",
      train_stores - store_stores)

print("Stores in store but not train:",
      store_stores - train_stores)

Stores in train but not store: set()
Stores in store but not train: set()

In [23]:
merged = df.merge(
    store,
    on="Store",
    how="left"
)

merged.shape

(1017209, 18)

In [24]:
merged.shape

(1017209, 18)